# Generated by Django 3.1.1 on 2020-09-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='salon',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='salon.address', verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
