# Generated by Django 3.1 on 2020-08-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientappointment',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Скидка на услугу'), (1, 'Скидка на услуги в определенные часы/дни'), (2, 'Скидка на первое посещение'), (3, 'Подарок'), (4, 'Подарок за первое посещение')], max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
