# Generated by Django 3.1 on 2020-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='site_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site URL'),
        ),
    ]
