# Generated by Django 3.0.8 on 2020-07-21 07:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='image_upload_path'),
        ),
    ]
