# Generated by Django 3.1 on 2020-08-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Опубликован на сайте?', verbose_name='Активный')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('salon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon', verbose_name='Салон')),
            ],
            options={
                'verbose_name': 'Клиент салона',
                'verbose_name_plural': 'Клиенты салона',
            },
        ),
    ]
