# Generated by Django 3.1 on 2020-08-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='salon',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Долгота'),
        ),
    ]
