# Generated by Django 3.0.8 on 2020-07-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'График работы'},
        ),
        migrations.AddField(
            model_name='workschedule',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salon.Salon', verbose_name='Салон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='working_hours_from',
            field=models.TimeField(default='09:00', verbose_name='Рабочие часы С'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='working_hours_to',
            field=models.TimeField(default='19:00', verbose_name='Рабочие часы ДО'),
        ),
    ]
