# Generated by Django 3.1 on 2020-08-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20200820_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salonservices',
            old_name='service',
            new_name='parent',
        ),
    ]
