# Generated by Django 3.1.1 on 2020-09-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20200922_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metro',
            old_name='metro_station',
            new_name='name',
        ),
    ]
