# Generated by Django 3.0.8 on 2020-07-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20200716_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.Salon', verbose_name='Салон'),
        ),
    ]
