# Generated by Django 3.1 on 2020-08-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_clientappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientappointment',
            name='status',
            field=models.CharField(blank=True, choices=[('cancelled', 'Отменен'), ('done', 'Исполнено'), ('in_progress', 'В процессе'), ('sign_up', 'Запись')], max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
