# Generated by Django 3.1 on 2020-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20200811_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='salon',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='salon',
            name='metro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
    ]
