# Generated by Django 3.0.8 on 2020-07-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='week_day',
            field=models.CharField(blank=True, choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], max_length=1, null=True, verbose_name='День недели'),
        ),
    ]
