# Generated by Django 3.1.1 on 2020-09-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_auto_20200924_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='longitude',
        ),
    ]
