# Generated by Django 3.1.1 on 2020-10-12 15:31

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('salon', '0003_auto_20200924_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservices',
            name='service',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services', verbose_name='Услуга'),
        ),
    ]
