# Generated by Django 3.0.8 on 2020-07-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20200721_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='week_day',
            field=models.CharField(blank=True, choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=50, null=True, verbose_name='День недели'),
        ),
    ]
