# Generated by Django 3.0.8 on 2020-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200717_1157'),
        ('salon', '0003_employee_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.Services', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='working_hours_from',
            field=models.TimeField(default='09:00', verbose_name='С'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='working_hours_to',
            field=models.TimeField(default='19:00', verbose_name='До'),
        ),
    ]
