# Generated by Django 3.1 on 2020-08-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_salonservices_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonservices',
            name='level',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='salonservices',
            name='tree_id',
        ),
    ]
