# Generated by Django 3.0.8 on 2020-07-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20200717_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True, help_text='Опубликован на сайте?', verbose_name='Активный'),
        ),
    ]
