# Generated by Django 3.0.8 on 2020-07-21 11:26

import apps.salon.models.employee
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20200721_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.salon.models.employee.image_upload_path),
        ),
    ]
