# Generated by Django 3.0.8 on 2020-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_auto_20200717_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(default=0, max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
