# Generated by Django 3.0.8 on 2020-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
