# Generated by Django 3.1.1 on 2020-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='action_type',
            field=models.CharField(blank=True, choices=[('0', 'Скидка на услугу'), ('1', 'Скидка на услуги в определенные часы/дни'), ('2', 'Скидка на первое посещение'), ('3', 'Подарок'), ('4', 'Подарок за первое посещение')], max_length=1, null=True, verbose_name='Тип акции'),
        ),
    ]
