# Generated by Django 3.0.8 on 2020-07-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_auto_20200717_1343'),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.Salon', verbose_name='Салон'),
        ),
    ]
