# Generated by Django 3.0.8 on 2020-07-17 12:37

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_actions_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actions',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='actions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
