# Generated by Django 3.1 on 2020-08-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('actions', '0002_actions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='action_type',
            field=models.CharField(choices=[(0, 'Скидка на услугу'), (1, 'Скидка на услуги в определенные часы/дни'), (2, 'Скидка на первое посещение'), (3, 'Подарок'), (4, 'Подарок за первое посещение'), (5, '')], default=0, max_length=1, verbose_name='Тип акции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actions',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services', verbose_name='Услуги'),
        ),
    ]
